# Generated by Django 5.1.2 on 2025-01-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0002_imagedata_imagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='desc',
            field=models.TextField(default='default description'),
        ),
    ]
