# Generated by Django 5.1.2 on 2025-01-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0003_imagedata_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagedata',
            old_name='image',
            new_name='imageval',
        ),
    ]
